unit Lissgv;

interface

var
credits: longint;
laderaum: longint;
mladeraum: longint;
chemikalien: word;
chemikalienpreis: word;
chemikalienmenge: word;
computer: word;
computerpreis: word;
computermenge: word;
energiezellen: word;
energiezellenpreis: word;
energiezellenmenge: word;
kunststoffe: word;
kunststoffepreis: word;
kunststoffemenge: word;
luxusgueter: word;
luxusgueterpreis: word;
luxusguetermenge: word;
metalle: word;
metallepreis: word;
metallemenge: word;
nahrungsmittel: word;
nahrungsmittelpreis: word;
nahrungsmittelmenge: word;
papier: word;
papierpreis: word;
papiermenge: word;
rauschgifte: word;
rauschgiftepreis: word;
rauschgiftemenge: word;
sklaven: word;
sklavenpreis: word;
sklavenmenge: word;
sprengstoff: word;
sprengstoffpreis: word;
sprengstoffmenge: word;
waffen: word;
waffenpreis: word;
waffenmenge: word;
wasser: word;
wasserpreis: word;
wassermenge: word;

laser: byte;
pixelprozug: byte;
maxschild:Longint;
mschild:Longint;
raumbomben:Longint;
photonentorpedos:Longint;
multiphasentorpedos:Longint;
neutronenemiterbombe:Longint;
fusionszellen:Longint;
implementation

end.
 